version: '3'
services:

  caddy:
    image: anybox/caddy:0.11.0
    restart: unless-stopped
    volumes:
      - caddy_ssl:/root/.caddy
      - ./caddy/conf/:/etc/caddy
      - ./caddy/www/:/srv

  haproxy:
    image: haproxy:1.8.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "1443:1443"
    volumes:
      - ./haproxy/conf/:/usr/local/etc/haproxy/
      - ./haproxy/www/:/var/www/

  rsyslog:
    image: rsyslog/syslog_appliance_alpine
    restart: unless-stopped
    volumes:
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - rsyslog_work:/work
      - ./rsyslog/logs:/logs


  consul:
    build: consul
    depends_on:
      - caddy
      - haproxy
    restart: unless-stopped
    network_mode: host
    environment:
        BTRFSDRIVER: anybox/buttervolume:latest
        CONSUL_LOCAL_CONFIG: '{
            "enable_script_checks": true,
            "watches": [{
                "type": "event",
                "handler_type": "script",
                "args": ["/handler.py"]}]
            }'
    volumes:
      - consul_docker_cfg:/home/consul/.docker
      - /run/docker.sock:/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - /deploy:/deploy
      - ./caddy/conf/:/consul/template/caddy/
      - ./haproxy/conf/:/consul/template/haproxy/

volumes:
  caddy_ssl:
    driver: anybox/buttervolume:latest
  caddy_srv:
    driver: anybox/buttervolume:latest
  consul_docker_cfg:
    driver: anybox/buttervolume:latest
  rsyslog_work:
    driver: local
