version: '3'
services:

  caddy:
    image: anybox/caddy:0.10.12
    restart: unless-stopped
    volumes:
      - caddy_ssl:/root/.caddy
      - ./caddy/conf/:/etc/caddy
      - caddy_srv/:/srv

  haproxy:
    image: haproxy:1.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "1443:1443"
    volumes:
      - ./haproxy/conf/:/usr/local/etc/haproxy/

  consul:
    build: consul
    depends_on:
      - caddy
      - haproxy
    restart: unless-stopped
    network_mode: host
    environment:
        CONSUL_LOCAL_CONFIG: '{
            "enable_script_checks": true,
            "watches": [{
                "type": "event",
                "handler_type": "script",
                "args": ["/handler.py"]}]
            }'
    volumes:
      - consul_docker_cfg:/home/consul/.docker
      - /run/docker.sock:/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - /deploy:/deploy
      - ./caddy/conf/:/consul/template/caddy/
      - ./haproxy/conf/:/consul/template/haproxy/
      - consul_ssh:/home/consul/.ssh

volumes:
  caddy_ssl:
    driver: btrfs
  caddy_srv:
    driver: btrfs
  consul_docker_cfg:
    driver: btrfs
  consul_ssh:
    driver: btrfs
